version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  define_file:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    docker:
      - image: circleci/node:13.8.0
    # Add steps to the job
    working_directory: /tmp
    steps:
      - run: touch inventory
      - run: echo "[all]" > inventory
      - persist_to_workspace:
          root: .
          paths:
            - inventory

  print_output_file:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    executor: aws-cli/default
    # Add steps to the job
    working_directory: /tmp
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          aws-region: AWS_REGION_NAME
      - run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' 
          --filters "Name=tag:Project,Values=udacity" 
          --output text >> inventory
      - run: cat inventory

# Orchestrate jobs using workflows
workflows:
  myworkflow:
    jobs:
      - define_file
      - print_output_file:
          requires: 
            - define_file
